### ISSUE TITLE
Is the nuspec docs on "latest version" incorrect?

### ISSUE THREAD

**Issue by togakangaroo** [NuGet/NuGetDocs#264]
See this [stackoverflow post](http://stackoverflow.com/questions/24765802/nuget-spec-dependencies-get-latest-version) 

In the [nuspec versioning docs](http://docs.nuget.org/docs/reference/versioning) I see

    ...
    (1.0,2.0) = 1.0 < x < 2.0
    [1.0,2.0] = 1.0 ≤ x ≤ 2.0
    empty = latest version.

I have a `packages.config` that looks like this
<?xml version="1.0" encoding="utf-8"?>

    <packages>
      <package id="psake" version="4.2.0.1" />
    </packages>

and I would like to change the version to "latest".

I've tried both 

    <packages>
      <package id="psake" version="" />
    </packages>

and

    <packages>
      <package id="psake" />
    </packages>

but both result in `Unable to parse version value '' from 'packages.config'.`

I am using Nuget.exe 2.8.2

Is this a bug or something wrong in the docs or am I doing it wrong?

**Comment by arpitgold** [comment]
Hi,

I am facing this issue too... Any updates on this ??

**Comment by jeffhandley** [comment]
packages.config does not support having a "floating" version specified.  Since NuGet burns references to package artifacts into your project at install time, and doesn't participate in build, these features are not supported.

We are working with the MSBuild and ASP.NET vNext teams to deliver the kind of experience you're wanting over time though.

http://blog.nuget.org/20141014/in-the-platform.html

**Comment by arpitgold** [comment]
Is there any alternate solution for this problem, where we can regularly update our packages and want to use latest version of package within allowed version.

**Comment by jeffhandley** [comment]
Not really.  ASP.NET vNext is paving the way for what the new workflows and features will look like.
